//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LBDataModel", "FK_tblOrderSummary_tblClients", "tblClient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LBM.Data.tblClient), "tblOrderSummary", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LBM.Data.tblOrderSummary), true)]
[assembly: EdmRelationshipAttribute("LBDataModel", "FK_tblOrders_tblOrders", "tblOrderSummary", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LBM.Data.tblOrderSummary), "tblOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LBM.Data.tblOrder), true)]
[assembly: EdmRelationshipAttribute("LBDataModel", "FK_tblOrders_tblProducts", "tblProduct", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LBM.Data.tblProduct), "tblOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LBM.Data.tblOrder), true)]

#endregion

namespace LBM.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LBDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LBDataEntities object using the connection string found in the 'LBDataEntities' section of the application configuration file.
        /// </summary>
        public LBDataEntities() : base("name=LBDataEntities", "LBDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LBDataEntities object.
        /// </summary>
        public LBDataEntities(string connectionString) : base(connectionString, "LBDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LBDataEntities object.
        /// </summary>
        public LBDataEntities(EntityConnection connection) : base(connection, "LBDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblClient> tblClients
        {
            get
            {
                if ((_tblClients == null))
                {
                    _tblClients = base.CreateObjectSet<tblClient>("tblClients");
                }
                return _tblClients;
            }
        }
        private ObjectSet<tblClient> _tblClients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblOrder> tblOrders
        {
            get
            {
                if ((_tblOrders == null))
                {
                    _tblOrders = base.CreateObjectSet<tblOrder>("tblOrders");
                }
                return _tblOrders;
            }
        }
        private ObjectSet<tblOrder> _tblOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblOrderSummary> tblOrderSummaries
        {
            get
            {
                if ((_tblOrderSummaries == null))
                {
                    _tblOrderSummaries = base.CreateObjectSet<tblOrderSummary>("tblOrderSummaries");
                }
                return _tblOrderSummaries;
            }
        }
        private ObjectSet<tblOrderSummary> _tblOrderSummaries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblProduct> tblProducts
        {
            get
            {
                if ((_tblProducts == null))
                {
                    _tblProducts = base.CreateObjectSet<tblProduct>("tblProducts");
                }
                return _tblProducts;
            }
        }
        private ObjectSet<tblProduct> _tblProducts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblClients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblClients(tblClient tblClient)
        {
            base.AddObject("tblClients", tblClient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblOrders(tblOrder tblOrder)
        {
            base.AddObject("tblOrders", tblOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblOrderSummaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblOrderSummaries(tblOrderSummary tblOrderSummary)
        {
            base.AddObject("tblOrderSummaries", tblOrderSummary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblProducts(tblProduct tblProduct)
        {
            base.AddObject("tblProducts", tblProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LBDataModel", Name="tblClient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblClient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblClient object.
        /// </summary>
        /// <param name="uID">Initial value of the UID property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        public static tblClient CreatetblClient(global::System.Int32 uID, global::System.String clientName)
        {
            tblClient tblClient = new tblClient();
            tblClient.UID = uID;
            tblClient.ClientName = clientName;
            return tblClient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UID
        {
            get
            {
                return _UID;
            }
            set
            {
                if (_UID != value)
                {
                    OnUIDChanging(value);
                    ReportPropertyChanging("UID");
                    _UID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UID");
                    OnUIDChanged();
                }
            }
        }
        private global::System.Int32 _UID;
        partial void OnUIDChanging(global::System.Int32 value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactEmail
        {
            get
            {
                return _ContactEmail;
            }
            set
            {
                OnContactEmailChanging(value);
                ReportPropertyChanging("ContactEmail");
                _ContactEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactEmail");
                OnContactEmailChanged();
            }
        }
        private global::System.String _ContactEmail;
        partial void OnContactEmailChanging(global::System.String value);
        partial void OnContactEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactPhoneNumber
        {
            get
            {
                return _ContactPhoneNumber;
            }
            set
            {
                OnContactPhoneNumberChanging(value);
                ReportPropertyChanging("ContactPhoneNumber");
                _ContactPhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactPhoneNumber");
                OnContactPhoneNumberChanged();
            }
        }
        private global::System.String _ContactPhoneNumber;
        partial void OnContactPhoneNumberChanging(global::System.String value);
        partial void OnContactPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AccountOpenDate
        {
            get
            {
                return _AccountOpenDate;
            }
            set
            {
                OnAccountOpenDateChanging(value);
                ReportPropertyChanging("AccountOpenDate");
                _AccountOpenDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountOpenDate");
                OnAccountOpenDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _AccountOpenDate;
        partial void OnAccountOpenDateChanging(Nullable<global::System.DateTime> value);
        partial void OnAccountOpenDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LBDataModel", "FK_tblOrderSummary_tblClients", "tblOrderSummary")]
        public EntityCollection<tblOrderSummary> tblOrderSummaries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrderSummary>("LBDataModel.FK_tblOrderSummary_tblClients", "tblOrderSummary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrderSummary>("LBDataModel.FK_tblOrderSummary_tblClients", "tblOrderSummary", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LBDataModel", Name="tblOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblOrder object.
        /// </summary>
        /// <param name="rowId">Initial value of the RowId property.</param>
        /// <param name="oID">Initial value of the OID property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="unitPrice">Initial value of the UnitPrice property.</param>
        /// <param name="orderClosed">Initial value of the OrderClosed property.</param>
        public static tblOrder CreatetblOrder(global::System.Int32 rowId, global::System.Int32 oID, global::System.Int32 productId, global::System.Int32 quantity, global::System.Double unitPrice, global::System.Boolean orderClosed)
        {
            tblOrder tblOrder = new tblOrder();
            tblOrder.RowId = rowId;
            tblOrder.OID = oID;
            tblOrder.ProductId = productId;
            tblOrder.Quantity = quantity;
            tblOrder.UnitPrice = unitPrice;
            tblOrder.OrderClosed = orderClosed;
            return tblOrder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RowId
        {
            get
            {
                return _RowId;
            }
            set
            {
                if (_RowId != value)
                {
                    OnRowIdChanging(value);
                    ReportPropertyChanging("RowId");
                    _RowId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RowId");
                    OnRowIdChanged();
                }
            }
        }
        private global::System.Int32 _RowId;
        partial void OnRowIdChanging(global::System.Int32 value);
        partial void OnRowIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OID
        {
            get
            {
                return _OID;
            }
            set
            {
                OnOIDChanging(value);
                ReportPropertyChanging("OID");
                _OID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OID");
                OnOIDChanged();
            }
        }
        private global::System.Int32 _OID;
        partial void OnOIDChanging(global::System.Int32 value);
        partial void OnOIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Int32 _ProductId;
        partial void OnProductIdChanging(global::System.Int32 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int32 _Quantity;
        partial void OnQuantityChanging(global::System.Int32 value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Double _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Double value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean OrderClosed
        {
            get
            {
                return _OrderClosed;
            }
            set
            {
                OnOrderClosedChanging(value);
                ReportPropertyChanging("OrderClosed");
                _OrderClosed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderClosed");
                OnOrderClosedChanged();
            }
        }
        private global::System.Boolean _OrderClosed;
        partial void OnOrderClosedChanging(global::System.Boolean value);
        partial void OnOrderClosedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LBDataModel", "FK_tblOrders_tblOrders", "tblOrderSummary")]
        public tblOrderSummary tblOrderSummary
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrderSummary>("LBDataModel.FK_tblOrders_tblOrders", "tblOrderSummary").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrderSummary>("LBDataModel.FK_tblOrders_tblOrders", "tblOrderSummary").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblOrderSummary> tblOrderSummaryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrderSummary>("LBDataModel.FK_tblOrders_tblOrders", "tblOrderSummary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblOrderSummary>("LBDataModel.FK_tblOrders_tblOrders", "tblOrderSummary", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LBDataModel", "FK_tblOrders_tblProducts", "tblProduct")]
        public tblProduct tblProduct
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProduct>("LBDataModel.FK_tblOrders_tblProducts", "tblProduct").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProduct>("LBDataModel.FK_tblOrders_tblProducts", "tblProduct").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProduct> tblProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProduct>("LBDataModel.FK_tblOrders_tblProducts", "tblProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProduct>("LBDataModel.FK_tblOrders_tblProducts", "tblProduct", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LBDataModel", Name="tblOrderSummary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblOrderSummary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblOrderSummary object.
        /// </summary>
        /// <param name="oID">Initial value of the OID property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="orderDateTime">Initial value of the OrderDateTime property.</param>
        public static tblOrderSummary CreatetblOrderSummary(global::System.Int32 oID, global::System.Int32 clientId, global::System.Double orderDateTime)
        {
            tblOrderSummary tblOrderSummary = new tblOrderSummary();
            tblOrderSummary.OID = oID;
            tblOrderSummary.ClientId = clientId;
            tblOrderSummary.OrderDateTime = orderDateTime;
            return tblOrderSummary;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OID
        {
            get
            {
                return _OID;
            }
            set
            {
                if (_OID != value)
                {
                    OnOIDChanging(value);
                    ReportPropertyChanging("OID");
                    _OID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OID");
                    OnOIDChanged();
                }
            }
        }
        private global::System.Int32 _OID;
        partial void OnOIDChanging(global::System.Int32 value);
        partial void OnOIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double OrderDateTime
        {
            get
            {
                return _OrderDateTime;
            }
            set
            {
                OnOrderDateTimeChanging(value);
                ReportPropertyChanging("OrderDateTime");
                _OrderDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDateTime");
                OnOrderDateTimeChanged();
            }
        }
        private global::System.Double _OrderDateTime;
        partial void OnOrderDateTimeChanging(global::System.Double value);
        partial void OnOrderDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OrderTotal
        {
            get
            {
                return _OrderTotal;
            }
            set
            {
                OnOrderTotalChanging(value);
                ReportPropertyChanging("OrderTotal");
                _OrderTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderTotal");
                OnOrderTotalChanged();
            }
        }
        private Nullable<global::System.Double> _OrderTotal;
        partial void OnOrderTotalChanging(Nullable<global::System.Double> value);
        partial void OnOrderTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> InvoiceDateTime
        {
            get
            {
                return _InvoiceDateTime;
            }
            set
            {
                OnInvoiceDateTimeChanging(value);
                ReportPropertyChanging("InvoiceDateTime");
                _InvoiceDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceDateTime");
                OnInvoiceDateTimeChanged();
            }
        }
        private Nullable<global::System.Double> _InvoiceDateTime;
        partial void OnInvoiceDateTimeChanging(Nullable<global::System.Double> value);
        partial void OnInvoiceDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PaymentReceivedDateTime
        {
            get
            {
                return _PaymentReceivedDateTime;
            }
            set
            {
                OnPaymentReceivedDateTimeChanging(value);
                ReportPropertyChanging("PaymentReceivedDateTime");
                _PaymentReceivedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentReceivedDateTime");
                OnPaymentReceivedDateTimeChanged();
            }
        }
        private Nullable<global::System.Double> _PaymentReceivedDateTime;
        partial void OnPaymentReceivedDateTimeChanging(Nullable<global::System.Double> value);
        partial void OnPaymentReceivedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OrderReceivedDateTime
        {
            get
            {
                return _OrderReceivedDateTime;
            }
            set
            {
                OnOrderReceivedDateTimeChanging(value);
                ReportPropertyChanging("OrderReceivedDateTime");
                _OrderReceivedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderReceivedDateTime");
                OnOrderReceivedDateTimeChanged();
            }
        }
        private Nullable<global::System.Double> _OrderReceivedDateTime;
        partial void OnOrderReceivedDateTimeChanging(Nullable<global::System.Double> value);
        partial void OnOrderReceivedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OrderDeliveredDateTime
        {
            get
            {
                return _OrderDeliveredDateTime;
            }
            set
            {
                OnOrderDeliveredDateTimeChanging(value);
                ReportPropertyChanging("OrderDeliveredDateTime");
                _OrderDeliveredDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDeliveredDateTime");
                OnOrderDeliveredDateTimeChanged();
            }
        }
        private Nullable<global::System.Double> _OrderDeliveredDateTime;
        partial void OnOrderDeliveredDateTimeChanging(Nullable<global::System.Double> value);
        partial void OnOrderDeliveredDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LBDataModel", "FK_tblOrderSummary_tblClients", "tblClient")]
        public tblClient tblClient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblClient>("LBDataModel.FK_tblOrderSummary_tblClients", "tblClient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblClient>("LBDataModel.FK_tblOrderSummary_tblClients", "tblClient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblClient> tblClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblClient>("LBDataModel.FK_tblOrderSummary_tblClients", "tblClient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblClient>("LBDataModel.FK_tblOrderSummary_tblClients", "tblClient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LBDataModel", "FK_tblOrders_tblOrders", "tblOrder")]
        public EntityCollection<tblOrder> tblOrders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrder>("LBDataModel.FK_tblOrders_tblOrders", "tblOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrder>("LBDataModel.FK_tblOrders_tblOrders", "tblOrder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LBDataModel", Name="tblProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblProduct object.
        /// </summary>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="unitPrice">Initial value of the UnitPrice property.</param>
        /// <param name="stockNumber">Initial value of the StockNumber property.</param>
        public static tblProduct CreatetblProduct(global::System.Int32 productId, global::System.String productName, global::System.Double unitPrice, global::System.Int32 stockNumber)
        {
            tblProduct tblProduct = new tblProduct();
            tblProduct.ProductId = productId;
            tblProduct.ProductName = productName;
            tblProduct.UnitPrice = unitPrice;
            tblProduct.StockNumber = stockNumber;
            return tblProduct;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Int32 _ProductId;
        partial void OnProductIdChanging(global::System.Int32 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Double _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Double value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StockNumber
        {
            get
            {
                return _StockNumber;
            }
            set
            {
                OnStockNumberChanging(value);
                ReportPropertyChanging("StockNumber");
                _StockNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockNumber");
                OnStockNumberChanged();
            }
        }
        private global::System.Int32 _StockNumber;
        partial void OnStockNumberChanging(global::System.Int32 value);
        partial void OnStockNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LBDataModel", "FK_tblOrders_tblProducts", "tblOrder")]
        public EntityCollection<tblOrder> tblOrders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrder>("LBDataModel.FK_tblOrders_tblProducts", "tblOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrder>("LBDataModel.FK_tblOrders_tblProducts", "tblOrder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LBDataModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="rowId">Initial value of the RowId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tblUser CreatetblUser(global::System.Int32 rowId, global::System.String username, global::System.String password)
        {
            tblUser tblUser = new tblUser();
            tblUser.RowId = rowId;
            tblUser.Username = username;
            tblUser.Password = password;
            return tblUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RowId
        {
            get
            {
                return _RowId;
            }
            set
            {
                if (_RowId != value)
                {
                    OnRowIdChanging(value);
                    ReportPropertyChanging("RowId");
                    _RowId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RowId");
                    OnRowIdChanged();
                }
            }
        }
        private global::System.Int32 _RowId;
        partial void OnRowIdChanging(global::System.Int32 value);
        partial void OnRowIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }

    #endregion

    
}
